#!/usr/bin/python
import os
import glob
import subprocess
import shutil
for logs in glob.glob("/var/log/*.gz"):
      os.remove(logs)
for updates in glob.glob('/root/sunil/*'):
   if os.path.isfile(updates):
         os.remove(updates)
   else:
         shutil.rmtree(updates)


for temp in glob.glob("/tmp/*"):
       if "/tmp/applieddir" in temp:
               print (temp)
       else:
               if os.path.isfile(temp):
                       os.remove(temp)
#       elif os.path.isdir(temp):
#               os.rmdir(temp)
               else:
                       shutil.rmtree(temp)
